-- Soccer Players Seed Part 2 (~75 players) — more European stars + Israeli league players
-- metadata keys: same schema as part 1

INSERT INTO public.players (name, sport, metadata) VALUES

-- ── Brazilian greats ───────────────────────────────────────────────────────────
('Kaka',                 'Soccer', '{"teams":["Sao Paulo","AC Milan","Real Madrid","Orlando City"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Roberto Carlos',       'Soccer', '{"teams":["Palmeiras","Inter Milan","Real Madrid","Fenerbahce","Anzhi"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Cafu',                 'Soccer', '{"teams":["Sao Paulo","Zaragoza","Roma","AC Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Dani Alves',           'Soccer', '{"teams":["Bahia","Sevilla","Barcelona","Juventus","PSG","Manchester City","Sao Paulo"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Ligue 1","Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Thiago Silva',         'Soccer', '{"teams":["RS Futebol","Juventude","Porto","Dynamo Moscow","Fluminense","AC Milan","PSG","Chelsea","Fluminense"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A","Ligue 1","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Marcelo',              'Soccer', '{"teams":["Fluminense","Real Madrid","Olympiacos"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Sergio Busquets',      'Soccer', '{"teams":["Barcelona","Inter Miami"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Lautaro Martinez',     'Soccer', '{"teams":["Racing Club","Inter Milan"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Julian Alvarez',       'Soccer', '{"teams":["River Plate","Manchester City","Atletico Madrid"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Alexis Sanchez',       'Soccer', '{"teams":["Cobreloa","Udinese","River Plate","Udinese","Barcelona","Arsenal","Manchester United","Inter Milan","Marseille","Udinese"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Premier League","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),

-- ── Portuguese legends ────────────────────────────────────────────────────────
('Luis Figo',            'Soccer', '{"teams":["Sporting CP","Barcelona","Real Madrid","Inter Milan"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Rui Costa',            'Soccer', '{"teams":["Fiorentina","AC Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Bruno Fernandes',      'Soccer', '{"teams":["Novara","Udinese","Sampdoria","Sporting CP","Manchester United"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Bernardo Silva',       'Soccer', '{"teams":["Benfica","Monaco","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── Spanish / La Liga stars ────────────────────────────────────────────────────
('Xabi Alonso',          'Soccer', '{"teams":["Real Sociedad","Liverpool","Real Madrid","Bayern Munich"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Cesc Fabregas',        'Soccer', '{"teams":["Arsenal","Barcelona","Chelsea","Monaco","Como"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),

-- ── Premier League stars ───────────────────────────────────────────────────────
('David Beckham',        'Soccer', '{"teams":["Manchester United","Real Madrid","LA Galaxy","AC Milan","PSG"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Rio Ferdinand',        'Soccer', '{"teams":["West Ham","Leeds United","Manchester United","QPR"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('John Terry',           'Soccer', '{"teams":["Chelsea","Aston Villa"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Virgil van Dijk',      'Soccer', '{"teams":["Groningen","Celtic","Southampton","Liverpool"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Eden Hazard',          'Soccer', '{"teams":["Lille","Chelsea","Real Madrid"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('N''Golo Kante',        'Soccer', '{"teams":["Boulogne","Caen","Leicester City","Chelsea","Al Ittihad"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Paul Pogba',           'Soccer', '{"teams":["Manchester United","Juventus","Manchester United"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Marcus Rashford',      'Soccer', '{"teams":["Manchester United"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Declan Rice',          'Soccer', '{"teams":["West Ham","Arsenal"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Riyad Mahrez',         'Soccer', '{"teams":["Le Havre","Quimper","Leicester City","Manchester City","Al Ahli"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Romelu Lukaku',        'Soccer', '{"teams":["Anderlecht","Chelsea","West Brom","Everton","Manchester United","Inter Milan","Chelsea","Roma","Inter Milan"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Sergio Aguero',        'Soccer', '{"teams":["Independiente","Atletico Madrid","Manchester City","Barcelona"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Hakim Ziyech',         'Soccer', '{"teams":["FC Eindhoven","Heerenveen","FC Twente","Ajax","Chelsea","Galatasaray","Paris FC"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── German stars ──────────────────────────────────────────────────────────────
('Ruud Gullit',          'Soccer', '{"teams":["Feyenoord","PSV","AC Milan","Sampdoria","Chelsea"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Ilkay Gundogan',       'Soccer', '{"teams":["Nuremberg","Borussia Dortmund","Manchester City","Barcelona","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Bundesliga","La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Timo Werner',          'Soccer', '{"teams":["VfB Stuttgart","RB Leipzig","Chelsea","RB Leipzig","Tottenham"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Leroy Sane',           'Soccer', '{"teams":["Schalke","Manchester City","Bayern Munich"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Jamal Musiala',        'Soccer', '{"teams":["Bayern Munich"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Florian Wirtz',        'Soccer', '{"teams":["Bayer Leverkusen","Bayern Munich"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Granit Xhaka',         'Soccer', '{"teams":["Basel","Borussia Monchengladbach","Arsenal","Bayer Leverkusen"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),

-- ── Italian / Serbian stars ────────────────────────────────────────────────────
('Andrea Barzagli',      'Soccer', '{"teams":["Palermo","Wolfsburg","Juventus"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Nemanja Vidic',        'Soccer', '{"teams":["Red Star Belgrade","Spartak Moscow","Manchester United","Inter Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Dejan Stankovic',      'Soccer', '{"teams":["Red Star Belgrade","Lazio","Inter Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Ivan Rakitic',         'Soccer', '{"teams":["Basel","Schalke","Sevilla","Barcelona","Sevilla"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Mario Mandzukic',      'Soccer', '{"teams":["Dinamo Zagreb","Wolfsburg","Bayern Munich","Atletico Madrid","Juventus","Al Duhail","AC Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Rafael Leao',          'Soccer', '{"teams":["Sporting CP","Lille","AC Milan"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Hakan Calhanoglu',     'Soccer', '{"teams":["Karlsruher SC","Hamburg","Bayer Leverkusen","AC Milan","Inter Milan"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),

-- ── African stars ─────────────────────────────────────────────────────────────
('Samuel Eto''o',        'Soccer', '{"teams":["Mallorca","Barcelona","Inter Milan","Anzhi","Chelsea","Everton","Sampdoria"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Yaya Toure',           'Soccer', '{"teams":["ASEC Mimosas","Beveren","Metalurh Donetsk","Olympiacos","Monaco","Barcelona","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Jay-Jay Okocha',       'Soccer', '{"teams":["Enugu Rangers","Eintracht Frankfurt","Fenerbahce","PSG","Bolton Wanderers","Hull City"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga","Ligue 1","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),

-- ── Latin American stars ───────────────────────────────────────────────────────
('Arturo Vidal',         'Soccer', '{"teams":["Colo-Colo","Juventus","Bayern Munich","Barcelona","Inter Milan","Flamengo"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A","Bundesliga","La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Achraf Hakimi',        'Soccer', '{"teams":["Real Madrid","Borussia Dortmund","Inter Milan","PSG"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A","Bundesliga","Ligue 1","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Martin Odegaard',      'Soccer', '{"teams":["Stromsgodset","Real Madrid","Heerenveen","Vitesse","Real Sociedad","Arsenal"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Lamine Yamal',         'Soccer', '{"teams":["Barcelona"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
-- ── Israeli players (played_israeli_league: true) ─────────────────────────────
('Yossi Benayoun',       'Soccer', '{"teams":["Maccabi Haifa","Racing Santander","Liverpool","Chelsea","West Ham","Arsenal","Queens Park Rangers","Maccabi Haifa","Hapoel Beer Sheva"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Eyal Berkovic',        'Soccer', '{"teams":["Maccabi Tel Aviv","Southampton","Celtic","West Ham","Manchester City","Blackburn Rovers","Portsmouth"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Haim Revivo',          'Soccer', '{"teams":["Maccabi Petah Tikva","Maccabi Tel Aviv","Celta Vigo","Fenerbahce","Napoli"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Ronny Rosenthal',      'Soccer', '{"teams":["Maccabi Haifa","Club Brugge","Standard Liege","Luton Town","Liverpool","Tottenham","Watford"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Nir Bitton',           'Soccer', '{"teams":["FC Ashdod","Celtic"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Tal Ben Haim',         'Soccer', '{"teams":["Maccabi Tel Aviv","Bolton Wanderers","Chelsea","Manchester City","Portsmouth","Sunderland","Queens Park Rangers"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Bibras Natcho',        'Soccer', '{"teams":["Bnei Yehuda","Anzhi","Rubin Kazan","CSKA Moscow","Hertha Berlin","Union Berlin","Partizan","Omonia Nicosia"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Bundesliga"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Manor Solomon',        'Soccer', '{"teams":["Maccabi Petah Tikva","Shakhtar Donetsk","Fulham","Leeds United"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Beram Kayal',          'Soccer', '{"teams":["Maccabi Haifa","Celtic","Brighton","Charlton Athletic","Maccabi Haifa"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Avi Nimni',            'Soccer', '{"teams":["Maccabi Tel Aviv","Beitar Jerusalem"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Walid Badir',          'Soccer', '{"teams":["Maccabi Haifa","Wimbledon","Maccabi Petah Tikva","Bnei Sakhnin","Maccabi Haifa"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Elyaniv Barda',        'Soccer', '{"teams":["Maccabi Haifa","Beitar Jerusalem","Groningen","Sporting Gijon","Maccabi Petah Tikva"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Eran Zahavi',          'Soccer', '{"teams":["Bnei Yehuda","Maccabi Netanya","Maccabi Tel Aviv","Hapoel Tel Aviv","Guangzhou Evergrande","Maccabi Tel Aviv","PSV","Utrecht","RB Leipzig"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Lior Refaelov',        'Soccer', '{"teams":["Maccabi Haifa","Club Brugge","Anderlecht","Antwerp","Royal Union SG","Maccabi Tel Aviv"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Itay Shechter',        'Soccer', '{"teams":["Beitar Jerusalem","Kaiserslautern","Schalke","Coventry City","Zulte Waregem","Maccabi Tel Aviv","Hapoel Haifa"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Bundesliga"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Ben Sahar',            'Soccer', '{"teams":["Chelsea","Espanyol","Sheffield Wednesday","Hapoel Tel Aviv","Maccabi Haifa","Beitar Jerusalem","Maccabi Netanya"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Maor Melikson',        'Soccer', '{"teams":["Bnei Yehuda","Dinamo Moscow","Maccabi Tel Aviv","Maccabi Haifa","Hapoel Beer Sheva"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Pini Balili',          'Soccer', '{"teams":["Maccabi Haifa","Omonia Nicosia","Bnei Yehuda","Real Zaragoza","Hapoel Tel Aviv","Maccabi Petah Tikva"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Shota Arveladze',      'Soccer', '{"teams":["Dinamo Tbilisi","Maccabi Tel Aviv","Ajax","Trabzonspor","Rangers","Alania Vladikavkaz","Deportivo"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":true,"national_captain":true,"no_ucl":true}'::jsonb),
('Toto Tamuz',           'Soccer', '{"teams":["Maccabi Haifa","Benfica","Maccabi Tel Aviv","Hapoel Tel Aviv","Maccabi Petah Tikva","FC Ashdod","Hapoel Haifa"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb),
('Salim Toama',          'Soccer', '{"teams":["Bnei Sakhnin","Maccabi Tel Aviv","Hapoel Tel Aviv","Hapoel Haifa","Hapoel Bnei Shefaram"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":true,"national_captain":false,"no_ucl":true}'::jsonb)

ON CONFLICT (name, sport) DO UPDATE
  SET metadata = EXCLUDED.metadata,
      active   = true;
