-- Soccer Players Seed Part 1 (~75 players) — European stars
-- metadata keys:
--   teams, ballon_dor, ucl_winner, world_cup_winner, league_title,
--   league_top_scorer, wc_golden_boot, season_30goals, ucl_50apps,
--   caps_100plus, top5_leagues (array), played_israeli_league,
--   national_captain, no_ucl

INSERT INTO public.players (name, sport, metadata) VALUES

-- ── All-time greats ───────────────────────────────────────────────────────────
('Lionel Messi',         'Soccer', '{"teams":["Barcelona","PSG","Inter Miami"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Cristiano Ronaldo',    'Soccer', '{"teams":["Sporting CP","Manchester United","Real Madrid","Juventus","Al Nassr"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Ronaldo Nazario',      'Soccer', '{"teams":["Cruzeiro","PSV","Barcelona","Inter Milan","Real Madrid","AC Milan","Corinthians"],"ballon_dor":true,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Eredivisie"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Zinedine Zidane',      'Soccer', '{"teams":["Cannes","Bordeaux","Juventus","Real Madrid"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Ronaldinho',           'Soccer', '{"teams":["Gremio","PSG","Barcelona","AC Milan","Flamengo","Atletico Mineiro"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Michel Platini',       'Soccer', '{"teams":["Nancy","Saint-Etienne","Juventus"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Johan Cruyff',         'Soccer', '{"teams":["Ajax","Barcelona","Los Angeles Aztecs","Washington Diplomats","Levante","Ajax","Feyenoord"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Eredivisie"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Franz Beckenbauer',    'Soccer', '{"teams":["Bayern Munich","New York Cosmos","Hamburg"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Marco van Basten',     'Soccer', '{"teams":["Ajax","AC Milan"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Gerd Muller',          'Soccer', '{"teams":["Bayern Munich","Fort Lauderdale Strikers"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── UCL winners / top European stars ─────────────────────────────────────────
('Luka Modric',          'Soccer', '{"teams":["Dinamo Zagreb","Tottenham","Real Madrid"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Robert Lewandowski',   'Soccer', '{"teams":["Lech Poznan","Borussia Dortmund","Bayern Munich","Barcelona"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Kylian Mbappe',        'Soccer', '{"teams":["Monaco","PSG","Real Madrid"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Neymar',               'Soccer', '{"teams":["Santos","Barcelona","PSG","Al Hilal"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Karim Benzema',        'Soccer', '{"teams":["Lyon","Real Madrid","Al Ittihad"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Erling Haaland',       'Soccer', '{"teams":["Molde","RB Salzburg","Borussia Dortmund","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Vinicius Junior',      'Soccer', '{"teams":["Flamengo","Real Madrid"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Kevin De Bruyne',      'Soccer', '{"teams":["Genk","Chelsea","Werder Bremen","Wolfsburg","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Sadio Mane',           'Soccer', '{"teams":["Metz","Southampton","Liverpool","Bayern Munich","Al Nassr"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Mohamed Salah',        'Soccer', '{"teams":["Basel","Chelsea","Fiorentina","Roma","Liverpool"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Harry Kane',           'Soccer', '{"teams":["Tottenham","Bayern Munich"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Antoine Griezmann',    'Soccer', '{"teams":["Real Sociedad","Atletico Madrid","Barcelona","Atletico Madrid"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Luis Suarez',          'Soccer', '{"teams":["Nacional","Groningen","Liverpool","Barcelona","Atletico Madrid","Gremio","Inter Miami","River Plate"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Eredivisie"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Gareth Bale',          'Soccer', '{"teams":["Southampton","Tottenham","Real Madrid","Cardiff City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Toni Kroos',           'Soccer', '{"teams":["Bayern Munich","Real Madrid"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── Premier League legends ────────────────────────────────────────────────────
('Thierry Henry',        'Soccer', '{"teams":["Monaco","Juventus","Arsenal","Barcelona","New York Red Bulls"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Wayne Rooney',         'Soccer', '{"teams":["Everton","Manchester United","DC United","Derby County"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Frank Lampard',        'Soccer', '{"teams":["West Ham","Chelsea","Manchester City","New York City FC"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Steven Gerrard',       'Soccer', '{"teams":["Liverpool","LA Galaxy"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Alan Shearer',         'Soccer', '{"teams":["Southampton","Blackburn Rovers","Newcastle United"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Peter Schmeichel',     'Soccer', '{"teams":["Gladsaxe-Hero","Brondby","Manchester United","Sporting CP","Aston Villa","Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Patrick Vieira',       'Soccer', '{"teams":["Cannes","AC Milan","Arsenal","Juventus","Inter Milan","Manchester City","New York City FC"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Didier Drogba',        'Soccer', '{"teams":["Le Mans","Guingamp","Marseille","Chelsea","Shanghai Shenhua","Galatasaray","Montreal Impact"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Dennis Bergkamp',      'Soccer', '{"teams":["Ajax","Inter Milan","Arsenal"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── La Liga legends ───────────────────────────────────────────────────────────
('Raul Gonzalez',        'Soccer', '{"teams":["Real Madrid","Schalke","Al Sadd","New York Cosmos"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Iker Casillas',        'Soccer', '{"teams":["Real Madrid","Porto"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Xavi Hernandez',       'Soccer', '{"teams":["Barcelona","Al Sadd"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Andres Iniesta',       'Soccer', '{"teams":["Barcelona","Vissel Kobe","Emirates Club","Internazionale Futbol"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Fernando Torres',      'Soccer', '{"teams":["Atletico Madrid","Liverpool","Chelsea","AC Milan","Atletico Madrid","Sagan Tosu"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":false,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('David Villa',          'Soccer', '{"teams":["Sporting Gijon","Zaragoza","Valencia","Barcelona","Atletico Madrid","New York City FC","Melbourne City","Vissel Kobe","Mineros de Zacatecas"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Carles Puyol',         'Soccer', '{"teams":["Barcelona"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Sergio Ramos',         'Soccer', '{"teams":["Sevilla","Real Madrid","PSG","Sevilla"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Diego Forlan',         'Soccer', '{"teams":["Independiente","Manchester United","Villarreal","Atletico Madrid","Inter Milan","Internacional","Penarol","Cerezo Osaka","Mumbai City"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Premier League","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),

-- ── Serie A legends ───────────────────────────────────────────────────────────
('Paolo Maldini',        'Soccer', '{"teams":["AC Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Francesco Totti',      'Soccer', '{"teams":["Roma"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Alessandro Del Piero', 'Soccer', '{"teams":["Juventus","Sydney FC","Delhi Dynamos"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Roberto Baggio',       'Soccer', '{"teams":["Vicenza","Fiorentina","Juventus","AC Milan","Bologna","Inter Milan","Brescia"],"ballon_dor":true,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Gabriel Batistuta',    'Soccer', '{"teams":["Boca Juniors","Fiorentina","Roma","Inter Milan","Al Arabi","Atletico Mineiro"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Filippo Inzaghi',      'Soccer', '{"teams":["Juventus","AC Milan"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":false,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Andrea Pirlo',         'Soccer', '{"teams":["Brescia","Inter Milan","AC Milan","Juventus","New York City FC"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Gianluigi Buffon',     'Soccer', '{"teams":["Parma","Juventus","PSG","Parma"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Serie A","Ligue 1"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Zlatan Ibrahimovic',   'Soccer', '{"teams":["Malmo","Ajax","Juventus","Inter Milan","Barcelona","AC Milan","PSG","Manchester United","LA Galaxy","Hammarby","AC Milan"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Ligue 1","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Fabio Cannavaro',      'Soccer', '{"teams":["Napoli","Parma","Inter Milan","Juventus","Real Madrid","Al Ahli","Al Ittihad"],"ballon_dor":true,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Serie A","La Liga"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),

-- ── Bundesliga legends ────────────────────────────────────────────────────────
('Oliver Kahn',          'Soccer', '{"teams":["Karlsruher SC","Bayern Munich"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Michael Ballack',      'Soccer', '{"teams":["Chemnitzer FC","Kaiserslautern","Bayer Leverkusen","Bayern Munich","Chelsea","Bayer Leverkusen"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Thomas Muller',        'Soccer', '{"teams":["Bayern Munich"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Manuel Neuer',         'Soccer', '{"teams":["Schalke","Bayern Munich"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Bundesliga"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Arjen Robben',         'Soccer', '{"teams":["Groningen","PSV","Chelsea","Real Madrid","Bayern Munich","Groningen"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":false,"top5_leagues":["Bundesliga","Premier League","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Franck Ribery',        'Soccer', '{"teams":["Boulogne","Ales","Stade Brestois","Metz","Galatasaray","Marseille","Bayern Munich","Fiorentina","Salernitana","Al Ittihad"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":true,"top5_leagues":["Bundesliga","Ligue 1","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── Ligue 1 stars ─────────────────────────────────────────────────────────────
('Ousmane Dembele',      'Soccer', '{"teams":["Rennes","Borussia Dortmund","Barcelona","PSG"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Bundesliga","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),

-- ── World Cup heroes / international stars ─────────────────────────────────
('Miroslav Klose',       'Soccer', '{"teams":["Kaiserslautern","Werder Bremen","Bayern Munich","Lazio"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Rivaldo',              'Soccer', '{"teams":["Santa Cruz","Mogi Mirim","Corinthians","Palmeiras","Deportivo","Barcelona","AC Milan","Cruzeiro","Olympiacos","AEK Athens","Bunyodkor","Kabuscorp","Sao Caetano"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Romario',              'Soccer', '{"teams":["Vasco da Gama","PSV","Barcelona","Valencia","Flamengo","Botafogo","Vasco da Gama","Fluminense","Miami FC","Adelaide United","America"],"ballon_dor":true,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Eredivisie"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Jurgen Klinsmann',     'Soccer', '{"teams":["VfB Stuttgart","Inter Milan","Monaco","Tottenham","Bayern Munich","Sampdoria","Orange County Blue Star"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":true,"league_title":true,"league_top_scorer":false,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Bundesliga","Serie A","Ligue 1","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Hristo Stoichkov',     'Soccer', '{"teams":["CSKA Sofia","Barcelona","Parma","CSKA Sofia","Al Nassr","Kansas City Wizards","Chicago Fire"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":true,"no_ucl":false}'::jsonb),
('Davor Suker',          'Soccer', '{"teams":["Osijek","Dinamo Zagreb","Sevilla","Real Madrid","Arsenal","West Ham","1860 Munich"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":true,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Premier League"],"played_israeli_league":false,"national_captain":true,"no_ucl":true}'::jsonb),
('Eusebio',              'Soccer', '{"teams":["Sporting de Lourenco Marques","Benfica","Boston Minutemen","Monterrey","Toronto Metros-Croatia","Las Vegas Quicksilvers","New Jersey Americans","União de Coimbra"],"ballon_dor":true,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":true,"season_30goals":true,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":[],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── Ajax / Dutch school ────────────────────────────────────────────────────────
('Patrick Kluivert',     'Soccer', '{"teams":["Ajax","AC Milan","Barcelona","Newcastle","Valencia","PSV","Lille"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["La Liga","Serie A","Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Ruud van Nistelrooy',  'Soccer', '{"teams":["Den Bosch","Heerenveen","PSV","Manchester United","Real Madrid","Hamburg","Malaga"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":true,"wc_golden_boot":false,"season_30goals":true,"ucl_50apps":true,"caps_100plus":false,"top5_leagues":["Premier League","La Liga","Bundesliga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Clarence Seedorf',     'Soccer', '{"teams":["Ajax","Sampdoria","Real Madrid","Inter Milan","AC Milan","Botafogo","Shenzhen"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":true,"caps_100plus":false,"top5_leagues":["La Liga","Serie A"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),

-- ── Current generation ─────────────────────────────────────────────────────────
('Pedri',                'Soccer', '{"teams":["Las Palmas","Barcelona"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Bukayo Saka',          'Soccer', '{"teams":["Arsenal"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":false,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb),
('Jude Bellingham',      'Soccer', '{"teams":["Birmingham City","Borussia Dortmund","Real Madrid"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Bundesliga","Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Phil Foden',           'Soccer', '{"teams":["Manchester City"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["Premier League"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Federico Valverde',    'Soccer', '{"teams":["Penarol","Real Madrid"],"ballon_dor":false,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Rodri',                'Soccer', '{"teams":["Villarreal","Atletico Madrid","Manchester City"],"ballon_dor":true,"ucl_winner":true,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":true,"top5_leagues":["Premier League","La Liga"],"played_israeli_league":false,"national_captain":false,"no_ucl":false}'::jsonb),
('Raphinha',             'Soccer', '{"teams":["Vitoria Guimaraes","Rennes","Leeds United","Barcelona"],"ballon_dor":false,"ucl_winner":false,"world_cup_winner":false,"league_title":true,"league_top_scorer":false,"wc_golden_boot":false,"season_30goals":false,"ucl_50apps":false,"caps_100plus":false,"top5_leagues":["La Liga","Premier League","Ligue 1"],"played_israeli_league":false,"national_captain":false,"no_ucl":true}'::jsonb)

ON CONFLICT (name, sport) DO UPDATE
  SET metadata = EXCLUDED.metadata,
      active   = true;
